name: "Build image: install-zfs-dkms-module"

env:
  IMAGE_NAME: "install-zfs-dkms-module"

on:
  pull_request:
    branches:
      - main
    paths:
      - install-zfs-dkms-module/*
      - .github/workflows/install-zfs-dkms-module.yml
  push:
    branches:
      - main
    paths:
      - install-zfs-dkms-module/*
      - .github/workflows/install-zfs-dkms-module.yml

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.IMAGE_NAME }}
          containerfiles: ${{ env.IMAGE_NAME }}/Containerfile
          image: ${{ env.IMAGE_NAME }}
          layers: false
          oci: true
